### ISSUE TITLE
FlowCrypt does not correctly load PGP encrypted messages sent by Sylpheed

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#2866] opened 2020-07-23 22:57 UTC
Support email: https://mail.google.com/mail/u/5/#inbox/FMfcgxwJWrXKXPChpktkMbKsRjcktrxB

Sylpheed uses the system's installed PGP tooling (`gpg` command) to send PGP encrypted messages. It's buggy but works. The problem is that it sends the PGP encrypted content, not in the email body, but as an unnamed attachment. It looks like this:

![Screenshot_2020-07-23_13-55-27](https://user-images.githubusercontent.com/44826516/88326958-344c8680-ccec-11ea-9896-c13df2f9f640.png)

If you were to paste the PGP message from the attachment into the body, FlowCrypt would understand it just fine. 

Sylpheed is kind of buggy in a number of other ways, and is pretty obscure. Nevertheless, no reason *not* to support it, and the problem may be us.

**Comment by tomholub** [comment] 2020-07-24 08:53
:+1: For all compatibility issues please arrange a sample message to be sent to our test email based on https://flowcrypt.com/docs/help/compatibility.html#incoming-email-from-other-software - ideally by asking the user to do it (less work) or alternatively yourself.

**Comment by tomholub** [comment] 2020-10-22 07:28
closing due to no sample to reproduce the issue

**Closed by tomholub** 2020-10-22 07:28 UTC
Labels: compatibility
