### ISSUE TITLE
cc and bcc do nothing / disappear when user clicks on them

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3115] opened 2020-11-02 21:03 UTC
ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwKjKmVhPNlKvFMCDktbLHrJplb

The user recorded the behavior and uploaded it into a video that clearly demonstrates the problem, including JS console output (there is none)

https://youtu.be/LJSRWnGGl00

**Comment by seisvelas** [comment] 2020-11-02 21:04
I tried to reproduce this in both Chrome and Firefox but was unable. The user is on firefox with flowcrypt version 7.9.8

**Comment by limonte** [comment] 2020-11-02 21:15
Unable to reproduce as well. The user got a couple of extensions along with FlowCrypt. One of them is Tampermonkey which can be used to run any user scripts. Could you maybe ask him to disable Tampermonkey and other extensions and try again?

**Comment by seisvelas** [comment] 2020-11-02 21:31
Thanks, I asked the user to do as you instructed. I'll update here when they get back to me

**Comment by seisvelas** [comment] 2020-11-20 00:19
The user disabled all other extensions and installed a fresh Firefox profile, but the issue persists

**Comment by tomholub** [comment] 2020-11-28 17:56
We'll have to close this as cannot reproduce. The user can try the following:
 - after this happens, check the browser console (F12) to see if any errors showed up
 - record a video (with a smartphone is enough) so that we can observe it

**Comment by seisvelas** [comment] 2020-11-29 06:22
@tomholub the user did indeed provide a video, in which the browser console is visible, though no appears appear there: https://youtu.be/LJSRWnGGl00

**Comment by limonte** [comment] 2020-11-29 06:57
Even though I can't reproduce the issue, I have an idea of what might be happening here, I'll tackle this PR.

**Closed** 2021-07-23 17:24 UTC
