### ISSUE TITLE
Couldn't decrypt message: Unknown ASCII armor type

### ISSUE THREAD

**Issue by liam-careerhub** [FlowCrypt/flowcrypt-browser#988] opened 2018-01-23 23:15 UTC
I received an encrypted email encrypted with OpenPGP

FlowCrypt (Google Inbox, Chrome) didn't decrypt it, with the error:
Message is either badly formatted or not compatible with FlowCrypt. 

`Unknown ASCII armor type`

There were browser console messages, but no errors:

`pgp_block.js:335 re-fetching message 16121e3b1a1bc4e1 from api because looks like bad formatting: full`
`pgp_block.js:335 re-fetching message 16121e3b1a1bc4e1 from api because looks like bad formatting: raw`

Tried manually on my PC using the command:
`gpg --output doc --decrypt email.pgp`
and my exported FlowCrypt key
And it decrypted fine to a file.

**Comment by tomholub** [comment] 2018-01-24 11:34
Can you please copy-paste the encrypted message and send it to us at
flowcrypt.compatibility@gmail.com - I'll take a look at the formatting.

**Comment by liam-careerhub** [comment] 2018-01-24 23:17
Thanks, Tom, I've sent it.

**Comment by tomholub** [comment] 2018-02-11 13:37
Sorry for getting back late, my guess is that the encrypted message was somehow copy-pasted with newlines messed up. It otherwise looks like a standard good encrypted message.

**Comment by tomholub** [comment] 2019-04-04 13:43
I'm closing this, could't reproduce.

**Closed by tomholub** 2019-04-04 13:43 UTC
