### ISSUE TITLE
Improve test results to contain failed assertion

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5058] opened 2023-04-04 17:12 UTC
We need to extract this meaningful piece into the test result:
```
  ✘ [fail]: compose - saving and rendering a draft with RTL text (plain text) [ALL RETRIES FAILED for compose - saving and rendering a draft with RTL text (plain text)]
    ℹ (attempt 1 of 1) Failed:   AssertionError: expected '<div><br></div><div><br></div><div>--…' to include '<div dir="rtl">مرحبا<br></div>'
          at <anonymous> (/home/osboxes/flowcrypt-browser/test/source/tests/compose.ts:1508:62)
          at <anonymous> (/home/osboxes/flowcrypt-browser/test/source/test.ts:81:11)
          at BrowserPool.BrowserPool.withNewBrowserTimeoutAndRetry (/home/osboxes/flowcrypt-browser/test/source/browser/browser-pool.ts:113:11)
          at <anonymous> (/home/osboxes/flowcrypt-browser/test/source/test.ts:75:7)
          at <async> <anonymous> (/test/source/tests/compose.ts:1495:39)
          at <async> <anonymous> (../test/source/test.ts:75:55)
```
The line with `(attempt x of x) Failed` (last attempt)

_Originally posted by @rrrooommmaaa in https://github.com/FlowCrypt/flowcrypt-browser/issues/5053#issuecomment-1495979454_

**Comment by rrrooommmaaa** [comment] 2023-04-04 19:00
duplicate of #5057

**Closed** 2023-04-04 19:35 UTC
