### ISSUE TITLE
allow use of keys with 3rd party revocation with a warning

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2676] opened 2020-03-17 13:27 UTC
keys like this https://github.com/openpgpjs/openpgpjs/issues/1046

Now that the throwing issue has been fixed and it will probably throw later (when verifying the signatures), there are a few options how to address this:

1) if the designated revocation signature is a separate one and can be removed from the key (+show warning), that would be preferred. Then we don't have to edit OpenPGP.js
2) if we would have to remove the whole signature including uid, then we'd basically have a situation like #1158
3) alternatively, if there was a sensible way to actually implement the protocol and be able to check against a designated revocation key, that would be nice, but unsure what the UX would look like - where to find the revoking key? Does user have to supply it, where does he find it? Do we keep a registry of them on Attester for user convenience? Many questions.
4) open to other ideas

For ux/styling, this comment provides some guidance: https://github.com/FlowCrypt/flowcrypt-browser/issues/1158#issuecomment-602273820

**Comment by tomholub** [comment] 2020-07-03 13:04
cusomer in my mailbox https://mail.google.com/mail/u/8/#inbox/FMfcgxwHMGMcqZwRJbltStsrqtFJPfTj

**Comment by wiktor-k** [comment] 2020-08-14 10:53
I can't reproduce that either with the key referenced in OpenPGP.js ticket (one needs to use [SKS pool key export](http://pool.sks-keyservers.net:11371/pks/lookup?search=0xfcf1db3a0b66b7a49448052601464811e1e80fd9&op=get) as Ubuntu keyserver seems to be dropping direct key signatures) or my own test key with `addrevoker` added.

It just works as if the revoker is not there.

Linked issue says it was fixed in OpenPGP.js 4.7 and we're using 4.10. Could that be the case? OpenPGP.js was updated in commit 97ce622877d6dcb521ec57f5378d6ad288a31162 in March and your last comment was made in July so it seems the customer had the issue after the update...

**Comment by tomholub** [comment] 2020-08-14 13:45
You're right, this appears to be fixed - this key can now be imported, and since we later strip 3rd party signatures, it seems to affect processing of the key itself and overall it seems to work well.

We could consider a warning when this happens, but given how rare such keys are, maybe the current situation is acceptable.

**Closed** 2020-08-14 13:45 UTC
Labels: PGP or S/MIME, actionable, compatibility
