### ISSUE TITLE
fix name of forwarded file when source file doesn't have internal PGP filename

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-browser#4915] opened 2023-01-30 08:01 UTC
Please look at https://github.com/FlowCrypt/flowcrypt-android/issues/2179

How it looks on the browser extension side

![image](https://user-images.githubusercontent.com/2863246/215418310-f7c4506c-bee7-492a-9388-101c2d48d1bd.png)

Original message structure

```EML
Subject: Issue 2179
Content-Type: multipart/mixed; boundary="00000000000097fc9005f3763b9f"

--00000000000097fc9005f3763b9f
Content-Type: text/plain; charset="UTF-8"

-----BEGIN PGP MESSAGE-----
Version: PGPainless

....
-----END PGP MESSAGE-----

--00000000000097fc9005f3763b9f
Content-Type: image/png; name="MainSignInFragmentEnterpriseFlowTest-testFesAvailabilityServerUpRequestTimeOut-d7c819f1-bc37-45b1-bf82-bef176a2dd33.png.pgp"
Content-Disposition: attachment; filename="MainSignInFragmentEnterpriseFlowTest-testFesAvailabilityServerUpRequestTimeOut-d7c819f1-bc37-45b1-bf82-bef176a2dd33.png.pgp"
Content-Transfer-Encoding: base64
Content-ID: <887721d6-1d85-4a27-8ee7-02db21df7f0a@flowcrypt>
X-Attachment-Id: 49de848874393375_0.1


--00000000000097fc9005f3763b9f--
```

encrypted Forwarded message

```EML
Subject: Fwd: Issue 2179
Date: Sun, 29 Jan 2023 23:35:49 -0800
MIME-Version: 1.0

------sinikael-?=_1-16750641490960.820897217671892
Content-Type: text/plain
Content-Transfer-Encoding: quoted-printable

-----BEGIN PGP MESSAGE-----
Version: FlowCrypt Email Encryption 8.4.2
Comment: Seamlessly send and receive encrypted email

....
-----END PGP MESSAGE-----

------sinikael-?=_1-16750641490960.820897217671892
Content-Type: application/octet-stream; name=_.pgp
Content-Disposition: attachment; filename=_.pgp
X-Attachment-Id: f_pwNefNSfsIExapXzRsWJWHiVlEQRND@flowcrypt
Content-Id: <f_pwNefNSfsIExapXzRsWJWHiVlEQRND@flowcrypt>
Content-Transfer-Encoding: base64


------sinikael-?=_1-16750641490960.820897217671892--
```

It would be nice to know why we receive `_.pgp`

A receiver can't open the forwarded attachment

![image](https://user-images.githubusercontent.com/2863246/215419309-42c0cc18-5625-440e-afb6-57fde3df3091.png)

One more detail. If the receiver will download the forwarded attachment(of course decrypt it before. It's possible on Android) and rename it to an original file extension(for example `_.pgp` to `image.png`) he will be able to read the content(see a picture). All of that means the encryption process works well. Just a problem with `_.pgp` extension.

**Comment by DenBond7** [comment] 2023-01-30 19:30
I meant the browser extension.

**Comment by tomholub** [comment] 2023-01-30 19:38
One thing to notice, that's some weird name: `MainSignInFragmentEnterpriseFlowTest-testFesAvailabilityServerUpRequestTimeOut-d7c819f1-bc37-45b1-bf82-bef176a2dd33.png.pgp`

**Comment by tomholub** [comment] 2023-01-30 19:50
In OpenPGP, there is a way to pass name of the encrypted file inside of the encrypted enclosure. I suspect you are maybe not passing any on Android, then it produces this as a default? Does PGPainless allow you to pass in the filename if it is a file that you are encrypting? If not or not sure, check with Paul.

**Comment by DenBond7** [comment] 2023-01-31 07:24
> One thing to notice, that's some weird name: MainSignInFragmentEnterpriseFlowTest-testFesAvailabilityServerUpRequestTimeOut-d7c819f1-bc37-45b1-bf82-bef176a2dd33.png.pgp but I guess that's just a test anyway.

It's a screenshot of some failed Android test.

>Here .... is -----BEGIN PGP ... and so on?

`MainSignInFragmentEnterpriseFlowTest-testFesAvailabilityServerUpRequestTimeOut-d7c819f1-bc37-45b1-bf82-bef176a2dd33.png.pgp` is an encrypted file(encrypted by FlowCrypt Android). It's not armored.

**Comment by DenBond7** [comment] 2023-01-31 07:44
> In OpenPGP, there is a way to pass name of the encrypted file inside of the encrypted enclosure. I suspect you are maybe not passing any on Android,

Yup, you are right. I don't pass any names.

>  then it produces this as a default? 

Nope. We have an empty file name here by default `private String fileName = "";`
https://github.com/pgpainless/pgpainless/blob/9f98e4ce371670d8cc05c5e9cdbd095d1b899271/pgpainless-core/src/main/java/org/pgpainless/encryption_signing/ProducerOptions.java#L20

> Does PGPainless allow you to pass in the filename if it is a file that you are encrypting?

Yes, it does. I will try it.

**Comment by tomholub** [comment] 2023-01-31 08:14
> > One thing to notice, that's some weird name: MainSignInFragmentEnterpriseFlowTest-testFesAvailabilityServerUpRequestTimeOut-d7c819f1-bc37-45b1-bf82-bef176a2dd33.png.pgp but I guess that's just a test anyway.
> 
> 
> 
> It's a screenshot of some failed Android test.
> 
> 
> 
> >Here .... is -----BEGIN PGP ... and so on?
> 
> 
> 
> `MainSignInFragmentEnterpriseFlowTest-testFesAvailabilityServerUpRequestTimeOut-d7c819f1-bc37-45b1-bf82-bef176a2dd33.png.pgp` is an encrypted file(encrypted by FlowCrypt Android). It's not armored.
> 
> 
> 
> 

i mean the message body that you removed from the sample with a "....."

**Comment by DenBond7** [comment] 2023-01-31 08:17
In that case `Here .... is -----BEGIN PGP ... and so on?` - yes

**Comment by tomholub** [comment] 2023-01-31 08:25
got it. yes then the name should help

**Comment by DenBond7** [comment] 2023-01-31 08:31
> got it. yes then the name should help

Yes. I can confirm it resolves the problem. In that case, I'm closing the current issue.

**Comment by tomholub** [comment] 2023-01-31 08:41
i'll open it here, as we could also improve it on browser extension

**Comment by tomholub** [comment] 2023-01-31 09:05
As far as browser extension, when forwarding:
 - if the received file has no internal pgp name
 - and it has an external name (in this case 
 - then use the external name minus `.pgp` as the name of the decrypted file

**Comment by tomholub** [comment] 2023-01-31 09:18
@DenBond7 when I forwarded your sample, and then tried to download the file from browser extension, it still produced `image.png.pgp` filename.

What exact filename have you set on android? The internal should be just `image.png` without the `.pgp`. The external should include `.pgp`

**Comment by DenBond7** [comment] 2023-01-31 09:22
> @DenBond7 when I forwarded your sample, and then tried to download the file from browser extension, it still produced image.png.pgp filename.
What exact filename have you set on android? The internal should be just image.png without the .pgp. The external should include .pgp

I've already fixed it. My last example doesn't contain the fix.

https://github.com/FlowCrypt/flowcrypt-android/blob/0a4fbf369f46f6fb8cb71ef33e430449d5348c0d/FlowCrypt/src/main/java/com/flowcrypt/email/service/ProcessingOutgoingMessageInfoHelper.kt#L292

**Comment by martgil** [comment] 2024-03-07 12:21
Hi @sosnovsky, just a quick question. I carefully tried to replicate this issue with the steps mentioned at https://github.com/FlowCrypt/flowcrypt-android/issues/2179 and I'm unable to reproduce the attachment with an underscore attachment name.

**Comment by sosnovsky** [comment] 2024-03-12 09:11
> Hi @sosnovsky, just a quick question. I carefully tried to replicate this issue with the steps mentioned at [FlowCrypt/flowcrypt-android#2179](https://github.com/FlowCrypt/flowcrypt-android/issues/2179) and I'm unable to reproduce the attachment with an underscore attachment name.

I wasn't able to reproduce mentioned issue too. Maybe it was fixed in some of our previous releases, as here it occurred in 8.4.2 build. I think it can be closed for now.

**Closed by sosnovsky** 2024-03-12 09:11 UTC
Labels: actionable
