### ISSUE TITLE
Chrome focus after sending encrypted email

### ISSUE THREAD

**Issue by circld** [FlowCrypt/flowcrypt-browser#1517] opened 2019-02-04 19:41 UTC
first off, huge thank you for an awesome extension! great idea and excellent execution. kudos.

**issue**
after replying to an encrypted message, the focus appears to interfere with Gmail shortcuts from registering/functioning. (this also impacts other extensions for driving using the keyboard, e.g., Vimium).

while this is a relatively minor issue (hitting tab a couple times and then attempting to shortcuts is a workaround), it is rather disruptive for power users used to driving Gmail almost entirely by keyboard.

**steps to reproduce**
1. enable Gmail shortcuts
2. focus on an encrypted conversation
3. use the `n` key to navigate down to the latest message in the conversation
4. press 'r' to reply to the message
5. type a message, press send (since `cmd-enter` is [not available as a shortcut](https://github.com/FlowCrypt/flowcrypt-browser/issues/183) yet, `tab` then `enter`)

at this point, the focus appears to be screwed up and no Gmail shortcuts work.

**system details**
OS: OSX
Browser: Version 72.0.3626.81 (Official Build) (64-bit)

**Comment by tomholub** [comment] 2019-02-05 15:04
That's interesting. We are open to contributions if someone wants to tackle this. We may also get to this ourselves sometime. Sorry to screw up your workflow!

**Comment by tomholub** [comment] 2019-02-05 15:05
If you are familiar with browser javascript, see if doing a vanilla JS equivalent to `$('body').focus()` in the dev console makes Gmail pick up on your shortcuts again. That would be good to know.

**Comment by circld** [comment] 2019-02-13 13:38
looks like upon sending a reply, the focus is on the body of the reply text:

<img width="542" alt="image" src="https://user-images.githubusercontent.com/5423134/52715467-27a5f980-2f62-11e9-8f03-9d0270b25a87.png">

running `> document.body.focus()` or `> $('body').focus()` doesn't seem to change the `document.activeElement`, nor restore shortcuts.

anything else you'd like me to try?

**Comment by tomholub** [comment] 2019-02-13 13:59
But were you attempting to focus on the body in the context if the inner iframe, or the Gmail page as a whole? Something to check.

Another thing to try: pick a Gmail element that is always there, that does not have any clickable buttons or links in it. Maybe the `Last account activity` on the bottom would be a good candidate. Try to issue a click programmatically on that element from the console. Would that restore shortcuts?

(if not, would clicking on it with your mouse fix the shortcuts?

**Comment by tomholub** [comment] 2019-09-27 09:37
Please verify this is still an issue, I have a feeling we may have fixed it.

**Comment by circld** [comment] 2019-09-29 03:23
I wonder whether the behavior I'm experiencing is specific to replying to myself while testing this. In other words, the focus is captured by the newly received message. After clicking on the sidebar on the right hand side (with add-ons), the "Your encrypted reply has been sent" notification disappears and shortcuts start to work again. Is any of this helpful?

**Comment by tomholub** [comment] 2019-09-29 10:34
Yes, it is definitely helpful. Thanks!

**Comment by limonte** [comment] 2019-10-04 10:50
Thanks a lot @circld for the detailed issue-report! The issue is fixed now and the fix will be released soon in v7.0.3

**Closed** 2019-10-04 10:55 UTC
Labels: actionable
