### ISSUE TITLE
secure compose button broken for some users

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4099] opened 2021-11-08 20:37 UTC
The new Gmail look breaks the Secure Compose button:

![image](https://user-images.githubusercontent.com/6059356/145248530-5eeaa1a6-18dd-4a2b-8aef-c023fdee1d35.png)

**Comment by limonte** [comment] 2021-11-11 08:14
Any additional details or screenshots would be useful in order to fix this issue.

**Comment by martgil** [comment] 2021-11-11 08:19
Hi @limonte,

We have a client sharing his experience on this. The Secure Compose button is missing from his Firefox browser even though the extension was installed successfully and also accessible from his toolbar.

![image](https://user-images.githubusercontent.com/46025304/141262577-2a4cc5ae-1bdf-41e3-ab4c-73e2283af730.png)

However, I'm not able to reproduce it from my end either even though we are using the same version of FlowCrypt extension for firefox. `FlowCrypt browser extension version 8.1.5 from my Firefox browser 94.0.`

![image](https://user-images.githubusercontent.com/46025304/141262766-97895c8d-e1b7-475e-b6fd-e6983f557e49.png)
 

Reference:
https://mail.google.com/mail/u/2/#inbox/FMfcgzGlkrwrQMVpcrPlBvPvBBswPHXs

**Comment by limonte** [comment] 2021-11-11 08:29
Thank you @martgil for the useful details!

I don't know how to reproduce Gmails's layout which is on the user's screenshot. Any help on how to get to the user's layout is welcome:

<img width="309" alt="CleanShot 2021-11-11 at 10 25 32@2x" src="https://user-images.githubusercontent.com/6059356/141263860-7347cc92-715f-45b8-a29f-9f023d7c4e61.png">

---

I can only get this one:

<img width="277" alt="CleanShot 2021-11-11 at 10 27 27@2x" src="https://user-images.githubusercontent.com/6059356/141264076-f6f6f217-b454-4ddb-b9ad-4c6b512da42f.png">

And this one:

<img width="283" alt="CleanShot 2021-11-11 at 10 29 19@2x" src="https://user-images.githubusercontent.com/6059356/141264325-d94e5286-f0c3-40b3-b22d-7a55dc4f373c.png">

In order to switch between these two layouts I use this setting:

![CleanShot 2021-11-11 at 10 28 17@2x](https://user-images.githubusercontent.com/6059356/141264296-0e175aa8-9cce-4e1b-a37a-690858a5ad19.png)

**Comment by martgil** [comment] 2021-11-11 09:32
Hi @limonte,

You're welcome! I will ask them as possible. I'm also on it right now trying to reproduce it. Hopefully, I can find it soon and share it with you asap.

**Comment by tomholub** [comment] 2021-11-11 10:26
Actually, what mart is sharing is a different issue. I'll share more details here when I get them.

**Comment by limonte** [comment] 2021-12-02 16:33
I guess by "broken" you mean this:

<img width="197" alt="CleanShot 2021-12-02 at 18 30 39@2x" src="https://user-images.githubusercontent.com/6059356/144463048-6c53679b-aab8-4975-9f17-2ed973575464.png">

Here's some investigation details, `div#flowcrypt_secure_compose_button` doesn't have any styles:

Broken button | Expected button
-|-
<img width="588" src="https://user-images.githubusercontent.com/6059356/144462999-2fe9cd88-58dd-4130-ba53-d760b1542fd6.png"> | <img width="588" alt="CleanShot 2021-12-02 at 18 31 49@2x" src="https://user-images.githubusercontent.com/6059356/144463246-06b3adf8-2bc2-4603-8372-d22b9bb5fd25.png">

**Comment by limonte** [comment] 2021-12-02 16:55
Gotcha! The customer have https://chrome.google.com/webstore/detail/virtru-email-protection/nemmanchfojaehgkbgcfmdiidbopakpp/related?hl=en installed, which conflicts with FlowCrypt. Investigating further...

**Comment by limonte** [comment] 2021-12-03 12:39
@tomholub I'm still not sure how to reproduce the issue and get this "broken" button. If you think that it might be fixed with #4162 then let's make that release and confirm with the client that with the new version the button is still broken. If so, then I'll most probably need additional input which would help to identify the cause.

**Comment by tomholub** [comment] 2021-12-03 12:44
I don't think it will fix the second issue. Can you schedule a meeting with the customer to do a remote screen? They are technical, and are motivated to help you get this fixed, so it's ok to do as many 2-hour meetings as you need until it's debugged and fixed.

**Comment by tomholub** [comment] 2021-12-03 12:45
They just cannot export their html like they did before and send it to us, because it happens on a real account.

**Comment by limonte** [comment] 2021-12-03 12:56
> I don't think it will fix the second issue. Can you schedule a meeting with the customer to do a remote screen? They are technical, and are motivated to help you get this fixed, so it's ok to do as many 2-hour meetings as you need until it's debugged and fixed.

Alright, will do 👍

**Closed** 2021-12-08 16:52 UTC
