### ISSUE TITLE
audit code to find OrgRules or other integration not currently covered by tests

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3070] opened 2020-10-21 11:19 UTC
The bug at https://github.com/FlowCrypt/flowcrypt-browser/issues/3066 was caused by the Sks class not covered by existing tests.

We should look at all of the API clients, as well as the various OrgRules we support, to make sure all reasonable combinations are covered by tests. The audit should be documented in this issue, and then separate issues will get created to address the shortcomings if any are found.

The first one that comes to mind:
 - [ ] currently Sks class is tested independently in unit tests but is not tested hollistically with the rest of the code based on the OrgRule that activates it. Should add a test on a new domain like `custom-sks-org-rule.flowcrypt.com` that also disables fetching from Attester on own domain, tests that pubkeys are being fetched from the Sks, that attester API is not called when querying own domain but called when querying other domain, and that the Sks integration is mentioned in FlowCrypt Settings -> Additional Settings -> Contacts.

**Comment by seisvelas** [comment] 2021-01-26 03:00
Here are the OrgRules combinations we currently test 

```
org-rules-test.flowcrypt.com:
    NO_PRV_CREATE
    NO_PRV_BACKUP
    ENFORCE_ATTESTER_SUBMIT
    USE_LEGACY_ATTESTER_SUBMIT

no-submit-org-rule.flowcrypt.com:
    NO_ATTESTER_SUBMIT

no-search-domains-org-rule.flowcrypt.com:
    disallow_attester_search_for_domains: [flowcrypt.com]
    
key-manager-autogen.flowcrypt.com:
    NO_PRV_BACKUP
    ENFORCE_ATTESTER_SUBMIT
    PRV_AUTOIMPORT_OR_AUTOGEN
    PASS_PHRASE_QUIET_AUTOGEN
    DEFAULT_REMEMBER_PASS_PHRASE

key-manager-server-offline.flowcrypt.com:
    NO_PRV_BACKUP
    ENFORCE_ATTESTER_SUBMIT
    PRV_AUTOIMPORT_OR_AUTOGEN
    PASS_PHRASE_QUIET_AUTOGEN
    DEFAULT_REMEMBER_PASS_PHRASE
    key_manager_url: https://localhost:8001/flowcrypt-email-key-manager
    enforce_keygen_algo: rsa2048
    disallow_attester_search_for_domains: [] 
    key_manager_url: https://localhost:1230/intentionally-wrong 
    
key-manager-no-pub-lookup.flowcrypt.com:
    NO_PRV_BACKUP
    ENFORCE_ATTESTER_SUBMIT
    PRV_AUTOIMPORT_OR_AUTOGEN
    PASS_PHRASE_QUIET_AUTOGEN
    DEFAULT_REMEMBER_PASS_PHRASE
    NO_KEY_MANAGER_PUB_LOOKUP
    key_manager_url: https://localhost:8001/flowcrypt-email-key-manager
    enforce_keygen_algo: rsa2048
    disallow_attester_search_for_domains: [] ] 
    
key-manager-keygen-expiration.flowcrypt.com 
    NO_PRV_BACKUP
    ENFORCE_ATTESTER_SUBMIT
    PRV_AUTOIMPORT_OR_AUTOGEN
    PASS_PHRASE_QUIET_AUTOGEN
    DEFAULT_REMEMBER_PASS_PHRASE
    key_manager_url: https://localhost:8001/flowcrypt-email-key-manager
    enforce_keygen_algo: rsa2048
    disallow_attester_search_for_domains: [] 
    enforce_keygen_expire_months: 1 
    
no-submit-org-rule.key-manager-autogen.flowcrypt.com: 
    NO_PRV_BACKUP
    ENFORCE_ATTESTER_SUBMIT
    PRV_AUTOIMPORT_OR_AUTOGEN
    PASS_PHRASE_QUIET_AUTOGEN
    DEFAULT_REMEMBER_PASS_PHRASE
    NO_ATTESTER_SUBMIT
    key_manager_url: https://localhost:8001/flowcrypt-email-key-manager
    enforce_keygen_algo: rsa2048
    disallow_attester_search_for_domains: []
    
prv-create-no-prv-backup.flowcrypt.com:
    NO_PRV_BACKUP
    enforce_keygen_algo: rsa2048
```

`custom_keyserver_url` is the only OrgRule that is never tested at all, as you mentioned.

I'm a bit unsure how to decide what should be tested. OrgRules are stored on the backend db, so we could look for popular OrgRules combos with a query like this:

```sql
select org_rules, count(org_rules) as count
from domain
group by org_rules
order by count
limit 10;
```

But I think that's not what you mean. Rather, I think we're looking for code that is only activated by specific combinations of OrgRules. So the goal would be to find everytime that happens in the code, and then test that code by activating that combination of OrgRules in the tests.

Is that correct?

If so, then I'll look through the codebase for situations where features are activated conditionally by an orgrule (or combination of orgrules) so we can test that those features work correctly when the relevant orgrule combo is present.

**Comment by tomholub** [comment] 2021-01-26 07:32
If we were looking for all combinations then we would come up with an endless amount of tests (and no doubt some cases that are not well handled in code), but that's not what I'm after.

I'd like to know if there is any particular OrgRule in https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/js/common/org-rules.ts - a flag like `ENFORCE_ATTESTER_SUBMIT` or other, or value like `enforce_keygen_algo` or other - that is not represented in tests at all, like `custom_keyserver_url`.

> custom_keyserver_url is the only OrgRule that is never tested at all, as you mentioned.

Got it - if you confirmed this, then that's all I wanted to know - thanks!

**Comment by tomholub** [comment] 2021-01-26 07:38
I'll make an issue for this

> The bug at #3066 was caused by the Sks class not covered by existing tests.
> 
> Currently Sks class is tested independently in unit tests but is not tested hollistically with the rest of the code based on the OrgRule that activates it.

- [ ] add a test on a new domain like `custom-sks-org-rule.flowcrypt.com` with org rules `custom_keyserver_url: (some mock url pretending to be SKS)`
- [ ] add one key to the SKS mock that is not present elsewhere in the mock
- [ ] test that the pubkey will be fetched from there with this rule enabled
- [ ] test that the SKS integration is mentioned in FlowCrypt Settings -> Additional Settings -> Contacts

**Comment by seisvelas** [comment] 2021-01-26 07:42
>Got it - if you confirmed this, then that's all I wanted to know - thanks!

Wow, turns out I way overthought this. In that case, yeah, I can confirm that `custom_keyserver_url` is the only one.

In that case, I'll go ahead and close this issue :)

**Closed by seisvelas** 2021-01-26 07:42 UTC
Labels: actionable, test would prevent past issue
