### ISSUE TITLE
Don't add "--" separator if user signature begins with "--"

### ISSUE THREAD

**Issue by loulan** [FlowCrypt/flowcrypt-browser#5368] opened 2023-08-17 15:59 UTC
FlowCrypt keeps adding "--" at the beginning of my signature. Which is unfortunate, because my signature already begins with "-- ". It's pretty ugly.

I believe correct behavior would be to not add anything to the signature?

**Comment by sosnovsky** [comment] 2023-08-17 18:17
Yeah, we're adding `--` in the beginning of signature to separate it from text content.
For fixing this case we should add check, and if signature text already begins with `--` then extension don't need to add additional `--` separator.
Thanks for reporting!

**Comment by sosnovsky** [comment] 2023-08-18 08:51
@loulan we re-checked our implementation and found that `--` shouldn't be added to your signature, if it's already starts with dashes `--`.
Can you please share your signature, so we can reproduce your issue? Or maybe just it's structure - is it single line or multiline, does it use html or it's plain one? Thanks

**Comment by sosnovsky** [comment] 2023-08-18 09:14
Hmm, interesting - I tried your signature and default Gmail compose adds additional `--`:

<img width="400" alt="Screenshot 2023-08-18 at 12 12 28" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/1062093/f6b40f72-c5e1-4a6d-a44d-7f066d6d8ff9">

While FlowCrypt has single line with dashes:

<img width="400" alt="Screenshot 2023-08-18 at 12 13 56" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/1062093/189a1c4d-05af-4566-8b7e-1b60a2fdaf2d">

Does default Gmail compose box add additional `--` for you too?

**Comment by loulan** [comment] 2023-08-18 09:15
The default gmail box doesn't add an additional `--`, flowcrypt does.

Maybe one difference is that it's HTML, as there is a link for my website.

**Comment by loulan** [comment] 2023-08-18 09:20
Here are screenshots:

<img width="238" alt="Capture d’écran 2023-08-18 à 11 18 51" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/365675/58beb5bb-32e2-4cfa-9e7f-dff577ebba99">

<img width="202" alt="Capture d’écran 2023-08-18 à 11 19 18" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/365675/9e34c529-4abf-42b6-8de9-1df67eff8830">

**Comment by martgil** [comment] 2023-08-18 09:23
Excuses,

Thanks @loulan I think I have found the issue. Could you please observe if there is an additional newline on the very top of the signature before the --:

![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/68959ac0-ac28-4f01-a11d-32b84c2d16d1)

**Comment by loulan** [comment] 2023-08-18 09:23
The signature starts with a newline, yes.

**Comment by loulan** [comment] 2023-08-18 09:35
I have the same problem without the newline.

<img width="215" alt="Capture d’écran 2023-08-18 à 11 33 47" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/365675/c21e8804-416c-4016-909f-3fcd696e5359">
<img width="183" alt="Capture d’écran 2023-08-18 à 11 34 18" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/365675/dd20d577-3d54-44f3-aae2-eeac7772e635">
<img width="190" alt="Capture d’écran 2023-08-18 à 11 34 28" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/365675/34f6f723-59a7-47c2-a01e-95a51ec1e5ff">

**Comment by sosnovsky** [comment] 2023-08-18 09:47
Do you have this checkbox checked in your signature settings?

<img width="480" alt="Screenshot 2023-08-18 at 12 45 58" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/1062093/4de78f4c-3684-4336-8594-dc9cb3dc13fc">

**Comment by loulan** [comment] 2023-08-18 09:49
Oh wow, I hadn't noticed this option... Yes, it's checked.

**Comment by sosnovsky** [comment] 2023-08-18 09:59
So now it's clear why `--` isn't added in default compose box, but I still can't reproduce additional `--` in FlowCrypt compose box.

Can you please send encrypted message with your signature (which has duplicated `--`) to flowcrypt.compatibility@gmail.com?

**Comment by loulan** [comment] 2023-08-18 10:01
Done.

**Comment by sosnovsky** [comment] 2023-08-18 10:06
Thanks! Checking it

**Comment by sosnovsky** [comment] 2023-08-18 10:50
@loulan do you have Firefox browser? We have a newer version of extension available for it (will be updated for Chrome soon too) - https://s3-us-west-2.amazonaws.com/cryptup-release/firefox/cryptup-io-firefox-8.5.0.xpi.
It'll be great if you can check it and see if duplicated `--` still present there or it's fixed

**Comment by loulan** [comment] 2023-08-18 11:17
I tried with FlowCrypt 8.5.0 on Firefox and I have the same problem.

**Comment by loulan** [comment] 2023-08-22 08:56
Interestingly, it seems that the issue disappears if the second line of my signature (after the initial newline) is just two hyphens and a new line, instead of two hyphens followed by a space and a newline.


I like keeping a space after the two hyphens though, as it is standard. See section "Standard delimiter" in: https://en.wikipedia.org/wiki/Signature_block


> The Usenet news system standards say that a signature block is conventionally delimited from the body of the message by a single line consisting of exactly two hyphens, followed by a space, followed by the end of line (i.e., in C-notation: "-- \n").[9][10][11] This latter prescription goes by many names, including “dash dash space”, "sig dashes", "signature cut line", "sig-marker", "sig separator" and "signature delimiter". It allows software to automatically mark or remove the sig block as the receiver desires.

**Comment by sosnovsky** [comment] 2023-08-22 12:22
I tried to reproduce, but it works well for me in both cases - with and without space after two hyphens.

Please also keep in mind that signature in FlowCrypt compose box isn't refreshed immediately after changing in settings, you probably need to reload page for fetching updated signature. So I also add some number (like `Test signature 1`, then `Test signature 2` etc) to be sure that signature was refreshed.

**Comment by loulan** [comment] 2023-08-22 12:23
I already do this, which is why there is "My name 2" in my screenshots above.

I'm really confused about why you can't reproduce this, it's very strange.

**Comment by loulan** [comment] 2023-08-22 12:40
Can I put a breakpoint somewhere in the developer tools or something like that to understand why the branch that should detect the "--" is not taken?

**Comment by sosnovsky** [comment] 2023-08-22 12:54
But for you it happens even without newline at the beginning of signature, so it should be some other reason

**Comment by martgil** [comment] 2023-08-26 05:49
@loulan Pardon me for bothering you. May I see how the FlowCrypt browser extension interprets your email footer? You can check this by going to [FlowCrypt settings](https://flowcrypt.com/docs/guide/common-tasks/open-settings.html) and clicking on the 'local_store' link button. After that, please kindly share the footer here starting from `"footer": "` until the closing `"` is reached, and paste it here. Please feel free to replace all personal information with dummy data. Thanks in advance.

![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/a8ec64f6-bde1-4aa8-b105-a8bce5357f8c)

**Comment by martgil** [comment] 2023-08-26 06:14
> Ah, I was able to reproduce it by adding space to the first empty line, so my signature looks like this:
> 
> ```
> <space>
> --<space>
> signature
> ```
> 
> If first space is removed, then second separator not added:
> 
> ```
> 
> --<space>
> signature
> ```

For me I'm able to replicate it when the signature already starts at `--` but with space:

<img width="392" alt="image" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/ba0d5d1e-8ee3-44bb-9532-b002ecfd6353">


<img width="329" alt="image" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/e701b71c-945d-4cac-93c3-92202742eca6">

**Comment by sosnovsky** [comment] 2023-08-26 16:56
> For me I'm able to replicate it when the signature already starts at -- but with space:

Oh, nice, can you then please implement fix so second separator won't be added in this case?

**Comment by loulan** [comment] 2023-08-26 17:07
Two points:
- I don't have a space on the first line.
- I forgot to reply regarding what's in `local_store`. I have multiple e-mail addresses there, but there is never two lines with double hyphens in `footer`. I.e., with replaced personal information:

"footer": "

-- 
My name
[http://my.website.com/](moz-extension://03296453-483e-4d31-b81b-ad2fe3a5d9c0/chrome/settings/modules/\"http://my.website.com/\")
"

I really don't understand why you guys don't manage to reproduce this. Maybe it's because I'm on a Mac and newlines are different? But I'm not sure it's the case in web browsers. I can't really think of anything else.

**Comment by loulan** [comment] 2023-08-26 17:10
Two points:
- I don't have a space on the first line.
- I forgot to reply regarding what's in `local_store`. I have multiple e-mail addresses there, but there is never two lines with double hyphens in `footer`. I.e., with replaced personal information:

```
"footer": "

-- 
My name
[http://my.website.com/](moz-extension://03296453-483e-4d31-b81b-ad2fe3a5d9c0/chrome/settings/modules/\"http://my.website.com/\")
"
```

Note that there are some old e-mail addresses above that I don't use anymore with an empty footer. Maybe your extension just looks at the first one to decide if a `--` is added, and since the first one has an empty footer, it adds `--` to all signatures, including the ones that already have an `--`?

If that isn't it, I really don't understand why you guys don't manage to reproduce this. Maybe it's because I'm on a Mac and newlines are different? But I'm not sure it's the case in web browsers. I can't really think of anything else.

**Comment by martgil** [comment] 2023-09-14 08:26
Hi @loulan,

We have created a custom FlowCrypt extension for you, as we assumed there might be a non-printable space character in your email signature's first line. To test it out, kindly unzip the compressed file and load it into your browser. You can choose either of the two options that suits you.

For Google Chrome browser, follow these steps:
1. Go to `chrome:extensions`
2. Enable developer mode
3. Click on the `Load unpacked` button
4. Choose the chrome-consumer folder

For Mozilla Firefox browser, follow these steps:
1. Go to `about:addons`
2. Click on Extensions
3. Click on the gear icon
4. Select "debug addons"
5. Click on "Load temporary add-on..."
6. Locate the firefox-consumer folder and load the manifest.json file

Once the extension is installed, please set it up and check if the issue no longer persists in this custom build. If the issue still exists, please go to the FlowCrypt settings, click on `local_store` at the bottom of the page, open the web developer tools, go to the console, and share the data from the JavaScript console with us via email at human@flowcrypt.com. Alternatively, you can write us an encrypted email through https://flowcrypt.com/me/tom.

<img width="564" alt="image" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/f74ff62c-2c67-4a27-b5f2-4a51f7613f6b">

FlowCrypt browser extension for Google Chrome: [chrome-consumer.zip](https://github.com/FlowCrypt/flowcrypt-browser/files/12606373/chrome-consumer.zip)
FlowCrypt browser extension for For Mozilla Firefox: [firefox-consumer.zip](https://github.com/FlowCrypt/flowcrypt-browser/files/12606375/firefox-consumer.zip)

Thank you for your time.
-Mart

**Comment by loulan** [comment] 2023-09-14 16:39
Thank you for your efforts.

It's still not working though. I sent you the output of JavaScript console by e-mail.

**Comment by martgil** [comment] 2023-09-15 05:57
Hello @loulan, thank you for sharing the JavaScript console logs with us. I was able to determine that the issue was caused by a non-breaking space ` `, which has a URL encoded value of `%C2%A0`.

You may not necessarily need to test the second custom build but feel free to do so.

[chrome-consumer.zip](https://github.com/FlowCrypt/flowcrypt-browser/files/12616030/chrome-consumer.zip)

**Closed** 2023-09-19 10:50 UTC
Labels: actionable

**Comment by martgil** [comment] 2023-09-19 10:58
This PR has been closed as resolved based on the proposed fix at #5412. Please feel free to re-open this GitHub issue if anyone experiences a similar issue.

**Comment by loulan** [comment] 2023-09-19 11:04
I confirm that the new version of the module fixed my issue. Thanks a lot!

There is still something I don't understand though. I was unhappy about having an unbreakable space instead of a space in my signature, so I wanted to fix that. I tried copy/pasting my signatures from the Gmail settings into text files and dumping their contents with `hexdump`, and they all contained spaces, i.e., `0x20`, not non-breaking spaces, i.e., `0xc2a0`. If I manually enter a non-breaking space with option+space into a text file and `hexdump` it, I see `0xc2a0`.

So how I end up with a non-breaking space in the `local_store` is a mystery!

**Comment by sosnovsky** [comment] 2023-09-19 11:50
Probably text editors convert such symbols as non-breaking spaces to plain spaces when pasting from other sources, as they usually remove text formatting on paste.
