### ISSUE TITLE
Unable to open attachment (.doc) in macOS 

### ISSUE THREAD

**Issue by p-acharya** [FlowCrypt/flowcrypt-browser#4031] opened 2021-10-01 15:13 UTC
OS: macOS Big Sur 11.2.3
Browser: Firefox w/ flowcrypt extension

trying to download an attached word doc. when i try to open it, I get the following:

<img width="807" alt="Select the encoding that makes your document readable." src="https://user-images.githubusercontent.com/28315147/135644600-085605ce-ed72-466b-8aa2-ce586169516b.png">

What should I do?

**Comment by limonte** [comment] 2021-10-04 11:24
@p-acharya thank you for reporting this issue. Unfortunately, I wasn't able to reproduce it in Firefox on macOS 11.6

Could you please specify the software you're trying to open the doc file with?

Also, is the issue happening for you only with that particular doc file or with all doc files?

Thanks!

**Comment by tomholub** [comment] 2021-11-13 17:11
Closing as cannot reproduce. Happy to look into it further if we get more info from @p-acharya

**Closed by tomholub** 2021-11-13 17:11 UTC
