### ISSUE TITLE
[Settings / Contact list] Unable to remove contacts

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3632] opened 2021-05-11 19:12 UTC
These buttons don't seem to work:

![image](https://user-images.githubusercontent.com/6059356/117871163-c175c180-b2a5-11eb-82ee-90eab0f08abd.png)

While fixing
 - add `title` attribute to all buttons (View, Edit, Remove), 
 - fix the buttons height which is currently a bit off:

![image](https://user-images.githubusercontent.com/6059356/117871393-00a41280-b2a6-11eb-8d2d-e598c74cb3bc.png)

**Comment by limonte** [comment] 2021-05-11 19:43
Also experiencing issues with rendering the contacts list, there are duplicates:

![image](https://user-images.githubusercontent.com/6059356/117874882-3ba84500-b2aa-11eb-8716-193fa85388a8.png)

**Comment by tomholub** [comment] 2021-05-11 20:02
Thank you for noticing the duplicates - filed an issue.

**Comment by limonte** [comment] 2021-05-18 08:46
@tomholub I was unable to fix the removing contact functionality, my knowledge of `ContactStore` isn't enough.

I'd assume that in `actionRemovePublicKey` should be `ContactStore.delete()` instead of `ContactStore.save()`, but `ContactStore.delete()` isn't implemented. I wasn't able to implement it, would appreciate some help here.

Small html/css fixes for issues mentioned in the issue descriptin are in #3649

**Comment by tomholub** [comment] 2021-05-18 11:16
No worries - thank you for the UI fixes. I'll assign to Roman to have a look.

**Comment by rrrooommmaaa** [comment] 2021-05-18 17:18
> I'd assume that in `actionRemovePublicKey` should be `ContactStore.delete()` instead of `ContactStore.save()`, but `ContactStore.delete()` isn't implemented. I wasn't able to implement it, would appreciate some help here.

That's right, `ContactStore.delete()` never existed and it is no longer possible to delete a pubkey with `save()` operation.
We introduced a new version of the storage that allows storing multiple pubkeys per contact, so it isn't enough to overwrite the "contact" with `{ email, pubkey: null }`
I suppose we need to implement the `delete()` method where we can specify explicitly the pubkey to be deleted (do we have an armored or parsed key in that form so we can pass it as an argument?)
Also, there is a possibility for a key to be shared between several contacts (emails).
Should we just unlink pubkeys or actually erase orphaned keys?

**Comment by rrrooommmaaa** [comment] 2021-05-20 08:34
> I suppose we need to implement the `delete()` method where we can specify explicitly the pubkey to be deleted (do we have an armored or parsed key in that form so we can pass it as an argument?)

Oh this is supposed to be "contact list", so deletion of a particular key should be on a contact details ("view") page

**Comment by tomholub** [comment] 2021-05-23 07:16
> > I suppose we need to implement the `delete()` method where we can specify explicitly the pubkey to be deleted (do we have an armored or parsed key in that form so we can pass it as an argument?)
> 
> Oh this is supposed to be "contact list", so deletion of a particular key should be on a contact details ("view") page

This is correct, deleting key by key, not person by person

**Comment by tomholub** [comment] 2021-05-23 07:19
> I suppose we need to implement the delete() method where we can specify explicitly the pubkey to be deleted 
> (do we have an armored or parsed key in that form so we can pass it as an argument?)

I would specify the key by fingerprint?

> Also, there is a possibility for a key to be shared between several contacts (emails).
> Should we just unlink pubkeys or actually erase orphaned keys?

I would unlink, from individual emails, unless user is unlinking from the last one. At that point I'd erase the key itself too.

**Comment by seisvelas** [comment] 2021-05-28 03:01
Also of note - when you receive an email with a key attached and the Update Key button appears, clicking the button also doesn't work to update the key.

ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGkXSSSbRFRkskTbVvjlqGgpXWS

**Comment by seisvelas** [comment] 2021-05-31 05:45
What is the best thing for users to do in case they need to update a key? They could manually delete the data from their browser's storage, or reinstall and add the contact with the new key?

Any workaround I can give to users in support who are having this issue?

**Comment by seisvelas** [comment] 2021-05-31 05:45
ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGkXSTfTjGQLqvVWSnZWqQXfhQV

**Comment by rrrooommmaaa** [comment] 2021-05-31 06:20
> What is the best thing for users to do in case they need to update a key? They could manually delete the data from their browser's storage, or reinstall and add the contact with the new key?
> 

As multiple keys are now allowed to be stored per contact, currently a sorting function is used to pick "the best key" for encryption. I suggest to implement a "preferred key" feature, making it possible to tick a desired key in contact settings,  so it won't be necessary to delete any keys.

**Comment by seisvelas** [comment] 2021-05-31 18:53
@rrrooommmaaa 

That may work, but what I mean is - what is the best thing for users to do right now while we wait for a proper fix to be pushed? What should our users do so they can work around this bug in the meantime?

**Comment by rrrooommmaaa** [comment] 2021-05-31 19:00
> What should our users do so they can work around this bug in the meantime?

The only thing I can think of is to manually delete the contact's entry from `emails` store of IndexedDB

![image](https://user-images.githubusercontent.com/23335944/120232141-9acef900-c25b-11eb-89ab-b55ed1706a34.png)

**Comment by seisvelas** [comment] 2021-06-01 01:51
Wonderful! Here is what I will tell people who report this:

---

Hi,

Thanks for reaching out to us - it turns out this behavior is caused by a bug in the browser extension that our developers are aware of and currently working to fix. In the meantime, there is a workaround. 

**Option 1)** You can delete a contact by opening the JavaScript Console on the FlowCrypt Settings page and paste in the following code:

```js
(emailAddress => {
    indexedDB.open('cryptup', 4).onsuccess = event => {
        console.log('Database successfully opened!')
        const db = event.target.result;
        db.transaction(["emails"], "readwrite")
            .objectStore("emails")
            .delete(emailAddress)
            .onsuccess = ev => {
                console.table(ev.target.result)
            }
    }
})('CONTACT TO DELETE')
```

Make sure to replace `CONTACT TO DELETE` with the email address of the contact you want to delete!

**Option 2)** You can manually delete a contact by doing into the browser's developer console -> Application -> Storage -> IndexedDB -> email, finding the contact, then right click and delete the entry, like so:

![image](https://user-images.githubusercontent.com/23335944/120232141-9acef900-c25b-11eb-89ab-b55ed1706a34.png)

We will let you know as soon as a fix has been issued. In the meantime, let us know if you have any trouble applying these instructions.

Thanks for your patience!
- Alex

---

For nontechnical users this might be very confusing, suggestions are welcome.

**Comment by rrrooommmaaa** [comment] 2021-06-01 06:28
we already have 'cryptup` version 5
```
indexedDB.open('cryptup', 5)
```

**Closed** 2021-06-04 08:50 UTC
Labels: actionable

**Comment by seisvelas** [comment] 2021-06-12 04:42
ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGkXSSTNCmGSNpkWkdvQFpKBNfp (wants to be alerted when new version released with fix)
