### ISSUE TITLE
[New Feature]Ability to communicate with local gpg-agent to redirect sign/decryption requests.

### ISSUE THREAD

**Issue by YanzheL** [FlowCrypt/flowcrypt-browser#1245] opened 2018-08-31 18:36 UTC
Is it possible to add a feature that every sign/decryption request is redirected to local gpg-agent, so that users can use their own local gpg-keyring and gpg-agent to process operations which require private key participation. By this way, FlowCrypt can beyond the limit of WebCrypto and get rid of some security concerns, because FlowCrypt has no need to manage user's private key and to do some critical operation. The role of FlowCrypt is just a proxy between gmail content and local gpg-agent.

I noticed that gpg-agent can be configured to listen on local TCP port, accepting client to communicate with it. So may be this feature is achievable by sending signing/decryption request to the tcp port that gpg-agent listen on. 

Another use case for this feature is that some users like me may use smart card (OpenPGP card) to store their private keys. These private keys are impossible to export. Use gpg-agent as backend will be simpler to help FlowCrypt to support smartcard based keys. Besides, attachment file encryption/decryption/sign can be done by native gpg, which is more efficient than JS.

What's more, there is no need for users to upload pubkey to your servers, for they can just upload to public PGP key server. Every time when user compose a email, FlowCrypt just lookup sender and recipient GPG keys from configured key server. It also save your money to store user's pubkey. 

A similar application that implemented this feature is "Enigmail". It can be configured to talk to local gpg-agent, but it's a desktop application. I prefer to Chrome extension like FlowCrypt, for it has better integration with GMail.

**Comment by YanzheL** [comment] 2018-09-01 14:11
gpg-agent uses UNIX domain socket on UNIX-like systems, TCP port on Windows.
It seems unable to listen on tcp port on UNIX-like systems, so it may be a little complicated to communicate with domain socket from JS. 
A possible solution is [Connecting to an already established UNIX socket with node.js](https://stackoverflow.com/questions/20807900/connecting-to-an-already-established-unix-socket-with-node-js)

Documentation about gpg-agent protocol:
[Agent-Protocol](https://www.gnupg.org/documentation/manuals/gnupg/Agent-Protocol.html#Agent-Protocol)

You plan to support smardcards in #964 , may be it can be implemented by this way. This solution is more generic, suited for all OpenPGP Cards.

**Comment by YanzheL** [comment] 2018-09-01 14:36
gpg-agent uses Assuan IPC protocol.
[Developing with Assuan](https://www.gnupg.org/documentation/manuals/assuan/)

**Comment by tomholub** [comment] 2018-09-25 08:59
Thanks for the writeup and details, it's helpful.

I will close this for now until I see more interest. If anyone stumbles upon this issue, please leave a comment saying that you would also like this implemented.

The reason I'm closing this for now is twofold: (1) I have always had a hard time working with gnupg (2) I think the possible benefits our userbase gets from this is too small compared to all of ways this can go wrong from the user experience point of view, plus our dev efforts.

However we still want to do #964. If it turns out the only reasonable way to implement that is to use gnupg, we may reconsider.

**Closed by tomholub** 2018-09-25 08:59 UTC

**Comment by strohel** [comment] 2018-10-23 14:15
Hi, I would also welcome this feature, or actually, this is a blocker for me using FlowCrypt.

The reason is that I don't want to give access to my private key to my browser and some of my keys are stored in hardware devices (YubiKey) which they could not (by design) leave.

Implementing gpg-agent communication would solve both issues at once.

**Comment by 0rkaM** [comment] 2019-08-10 02:16
+1 for me too.
That is why I am using Mailvelope:
[Using GnuPG backend instead of OpenPGP.js?](https://www.mailvelope.com/en/faq#gnupg)

**Comment by YanzheL** [comment] 2019-08-17 09:00
> +1 for me too.
> That is why I am using Mailvelope:
> [Using GnuPG backend instead of OpenPGP.js?](https://www.mailvelope.com/en/faq#gnupg)

Thanks, that's cool.
I'm switching to Mailvelope now, it is exactly what I want.

**Comment by tomholub** [comment] 2019-08-17 11:54
Yup, Mailvelope has this functionality, so I would recommend using their extension for the time being when this is a hard requirement. Then you can re-evaluate FlowCrypt later. 

Most folks want this for hw token integration, which we're planning either way (on Android too). On desktop, that probably means integrating with gpg-agent, which can allow other use cases as a side effect.
