### ISSUE TITLE
Error: could not properly parse signed message

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#2931] opened 2020-09-03 04:43 UTC
Ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwJXLdhpfNMDkqhRLbDrVMDhJnJ

> Hi There
> 
> Thanks for the work. Testing by mailing myself works fine most of the time.
> I can read signed and encrypted+signed messages to myself (from Flowcrypt,
> account tingleff.jens@gmail to jensting@tingleff.org) . I can read an
> encrypted+signed message in the other direction (from jensting to
> tingleff.jens). But, signed only from jensting to tingleff.jens shows bad
> signature.
> 
> There are multiple email accounts associated with the key, I'm using
> Evolution on Gnome (fedora linux) to send from jensting@tingleff.org. The
> message below fails signature test when I try to read it - is it simply me
> not having my own public key ring (i.e. the one from Linux)?

**Comment by tomholub** [comment] 2020-09-16 13:19
Since this issue occurs when sending a signed message from other software to be opened by FlowCrypt, this applies:
https://flowcrypt.com/docs/help/compatibility.html#incoming-email-from-other-software

Please ask the user to send a particularly short message, like "1234" that will make it much easier for us to debug the structure and find out why is there a compatibility issue. Should be titled `signed-only message from Evolution on Gnome cannot be parsed`

**Comment by tomholub** [comment] 2020-10-22 07:31
closing, missing sample to reproduce. If the user sent one, pls link it in this issue and reopen.

**Closed by tomholub** 2020-10-22 07:31 UTC
