### ISSUE TITLE
Flowcrypt does not validate the signature because of the space after two dashes in my signature

### ISSUE THREAD

**Issue by epreci** [FlowCrypt/flowcrypt-browser#1736] opened 2019-05-31 13:45 UTC
When I try to sign (no encryption) and send an email from Thunderbird (using Enigmail) to Gmail on Firefox (using Flowcrypt), Flowcrypt does not validate the signature because of the space after two dashes in my signature.

i.e:

--space
Mr. test
Adr:test2

Error message: 
**Signature does not match**

![Flowcrypt](https://user-images.githubusercontent.com/51236861/58709726-0bb44f80-83bb-11e9-81f3-1c2938a44aa9.JPG)

**Comment by tomholub** [comment] 2019-05-31 14:57
I think it's not just that. I'd you simply only send "test", without any dashes, does it validate?

**Comment by epreci** [comment] 2019-05-31 15:05
Yes you are right! It does not validate the simple text either. Is this a bug, or I didn't configure it properly?

**Comment by tomholub** [comment] 2019-05-31 15:26
It's a bug. I'll close this as a duplicate of #1667

We'll look into it soon. Thanks for reporting!

**Closed by tomholub** 2019-05-31 15:26 UTC
