### ISSUE TITLE
Update emailjs-mime-builder to the newer version

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#1916] opened 2019-08-12 14:12 UTC
CC is working now, but I've got a problem with BCC.
We are using an old version of `emailjs-mime-builder` and to make it work I need to update it to the newer one.

I will create another PR for that

_Originally posted by @michael-volynets in https://github.com/FlowCrypt/flowcrypt-browser/issues/1065#issuecomment-520440363_

**Comment by michael-volynets** [comment] 2019-08-12 14:12
#1065

**Comment by michael-volynets** [comment] 2019-08-12 15:25
@tomholub Did you maybe make any changes in our `emailjs-mime-builder.js` (https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/lib/emailjs/emailjs-mime-builder.js) because I checked the same file on their repository and it's a little bit different. 
Here is their file: https://github.com/emailjs/emailjs-mime-builder/blob/master/dist/builder.js
Seems like you have built the source files another way, haven't you?

**Comment by michael-volynets** [comment] 2019-08-12 15:35
I saw the answer in the related issue

**Comment by tomholub** [comment] 2019-08-12 16:09
I self-assigned this to address later

**Comment by tomholub** [comment] 2019-11-01 10:55
duplicate of #1748

**Closed by tomholub** 2019-11-01 10:55 UTC
Labels: actionable
