### ISSUE TITLE
Possibility to work together with Grammarly

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#1903] opened 2019-08-12 08:22 UTC
[Grammarly](https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen?hl=en) is one of the most popular Chrome extensions, 10+ millions of users are using it for writing better emails.

It works when I'm writing the native Gmail email:

![image](https://user-images.githubusercontent.com/6059356/62852721-edd86480-bcf2-11e9-9cf5-98c538748f9a.png)

As I understand correctly, Grammarly injects itself to every textarea, e.g. right now when I'm writing the GitHub issue.

But for some reason, FlowCrypt popup is preventing Grammarly from injecting itself.

Is it technically possible to have the FlowCrypt and Grammarly working together?

**Comment by tomholub** [comment] 2019-08-12 16:56
Yes, I keep getting this request.

The problem is that Grammarly will send your chunks of text to their backend. Being a security extension, I'm not particularly thrilled to add support.

We could though... people keep asking it.. I don't even think why Grammarly doesn't work. Maybe they don't scan sub-frames. Maybe they have no access to frames of other extensions, so that would be a hard limitation. If we somehow integrated it, this would 100% have to be first presented to user, and they would have to agree with it. There would have to be a big fat red warning that Grammarly sends their text to their backend and therefore we cannot guarantee safety of their data while it's in use. There should then always be a banner on top of secure compose warning them that Grammarly is enabled & giving them a one-click way to cancel.

Given all of this.. maybe it's a #wontfix again..

**Comment by tomholub** [comment] 2019-08-12 16:57
I'll leave it open this time though.

**Comment by tomholub** [comment] 2020-08-14 14:05
I'll close this again, sorry!

**Closed by tomholub** 2020-08-14 14:05 UTC
